### ISSUE TITLE
Video Link Is Broken

### ISSUE THREAD

**Issue by puskuruk** [tenderlove/analog-terminal-bell#1]
I watched the video from Twitter(It was so good😂) but the YouTube link in the README is broken. 🤫

<img width="1286" alt="Screen Shot 2020-09-08 at 19 09 19" src="https://user-images.githubusercontent.com/22892227/92501360-1c32b700-f207-11ea-947d-a443772b119b.png">

**Comment by tenderlove** [comment]
Oops!!! Thanks, I'll fix it now.  I guess this is how "product" launches go

**Comment by tenderlove** [comment]
Fixed!
