### ISSUE TITLE
Solenoid doesn't fit in case

### ISSUE THREAD

**Issue by larsbrinkhoff** [tenderlove/analog-terminal-bell#7]
Maybe my 3D printer isn't top notch (UltiMaker 2), but I couldn't get the solenoid to fit.

I solved it by setting the GPIO output high, making the soleniod warm enough that it would soften the PLA and I could then force it down.

**Comment by tenderlove** [comment]
Huh, did you use the same solenoid from the parts list?  I wonder if they changed the ones they're selling? 😬

**Comment by larsbrinkhoff** [comment]
Yes, I ordered everything straight from your official parts list.  Could well be variations in supplier or something.

Anyway, no big deal.  Just FYI.
